### ISSUE TITLE
Upgrading from 1.0.0 to 2.0.0

### ISSUE THREAD

**Issue by killia15** [fasiha/ebisu#24]
Hello! I have a quick question about upgrading. Previously, calling the updateRecall function looked like this: `new_alpha, new_beta, new_half_life = updateRecall((alpha, beta, half_life), correct, hours_since_last_update)` but now it is changed to `new_alpha, new_beta, new_half_life = updateRecall((alpha, beta, half_life), total_correct, total_overall, hours_since_last_update)` where `hours_since_last_update` is the number of hours since the model (alpha, beta, half_life) was last calculated. 

Are the model values still good from version 1.0.0 and should I be aware of any other breaking changes?

Thanks! Fantastic library btw.

**Comment by fasiha** [comment]
Yes! The models should be reused, I’ll make a note about that in the changelog.

And yes, your summary of the change is the only difference—instead of a boolean you pass in two integers; everything else is the same. You can recover the previous behavior by always setting your `total_overall` to 1, and adjusting `total_correct` for quiz.
