### ISSUE TITLE
Noob Question, should tnow in updateRecall be set to 0 if first time showing the question?

### ISSUE THREAD

**Issue by jahamed** [fasiha/ebisu#37]
Trying to prototype a simple quiz app where a user is presented facts and basically says "know it" or "don't know it".

Then I was planning on updating the recall % for each question and repeating questions they don't know over a certain %.

But what happens if it's the first time showing a user the question? How can I properly updateRecall when I have no time delta from the last time they saw the question?

Should I just set it to 0 or something else?

**Comment by fasiha** [comment]
Ah, no, this question pops up a lot, and we haven't improved the docs yet to highlight it, but:

First time you show a card, you can use `ebisu.defaultModel` to create the initial model ([docs](https://github.com/fasiha/ebisu/blob/gh-pages/doc/doc.md#defaultmodelt-alpha30-betanone)).

Then you can call `ebisu.updateRecall`, since you have a model. Does that help?

**Comment by jahamed** [comment]
Ah sorry still confused 😕 

So every question should have it's own model or are they shared between all the questions?
>// Question 1
> questionModel = ebisu.defaultModel(15);
> ebisu.updateRecall(questionModel, 1, 1, 0); // 1 try, 1 success

But I can't set the 'elapsed' time in updateRecall to 0.

Just trying to figure out the flow for a basic yes/no quiz app that works a bit like Anki for example.

p.s - do you know of any other projects using ebisu like this so I could learn from their code?

Thanks!

*Edit
Do I just have a core misunderstanding about how Ebisu works?
Does a user need to 'learn' a fact before they can be quizzed on it? I was hoping to rebuild a simple Anki webapp clone with just 👎 / 👍  for example

**Comment by fasiha** [comment]
> So every question should have it's own model or are they shared between all the questions?

Each question/flashcard has its own model. Because you want `predictRecall` to give you a different number for each flashcard/model right?

> p.s - do you know of any other projects using ebisu like this so I could learn from their code?

There's a bunch but maybe Meguro is the simplest: it's a Node.js command-line script that just reads and updates a text file containing flashcards/models: https://github.com/fasiha/meguro/ feel free to ask if anything is confusing. The [`index.js`](https://github.com/fasiha/meguro/blob/master/index.js) is <100 lines of JavaScript.

> Does a user need to 'learn' a fact before they can be quizzed on it?

`updateRecall` does need a model and non-zero `tnow` to update the quiz model, but this doesn't mean your app *needs* a separate learn-then-quiz workflow. If your app wanted to keep Anki's style of "learn new facts, then get quizzed", you'd create a new model with `defaultModel` for each card when the user first indicated they learned them. But that's not required—you can pre-initialize each flashcard with a model if you can assume the user knows them all?

I really need to push out version 2.1 with a function to let you *scale* halflives, I think that's a really useful feature for real quiz apps like your Anki clone and Meguro—it's useful because, a lot of times, you'll pick the same initial model with `defaultModel` but in fact the user will know some cards a lot better than others. Scaling the halflife in Ebisu lets your app tell Ebisu to stretch out a model to a new halflife: you can specify any number to scale, so your app might map an "easy" quiz to 2x scale and a "hard" quiz to 0.5x scale. This isn't in Ebisu right now, it's been in a branch for a few months—I'm going to try and get it shipped this week. The code's done, it just takes me a long time to write the docstrings and update the README with the details…

Feel free to get in touch with any more questions.

**Comment by jahamed** [comment]
Thanks for responding so fast! In Thailand right now so thought this would take a while.

Yeah hopefully not bugging you too much. I see the potential of this library since algos like sm2/anki are too strict/based on due dates for casual quiz apps/users. And surprisingly with SRS getting more popular there aren't many prebuilt libraries... So thanks a lot for making this 😄... the math is flying over my head.

> Each question/flashcard has its own model. Because you want predictRecall to give you a different number for each flashcard/model right?

Assuming all the priors are the same the prediction only depends on time elapsed since last review right? And with a starting default model for each question all predictions will be the same at the start. For my app I can't really assume anything about what the user knows. I was hoping to quiz them / help them learn at the same time.

Not sure if it helps but here's a quick idea what I have so far for perspective:

![image](https://user-images.githubusercontent.com/794542/97810570-62f0da80-1ca7-11eb-9b72-fd4f3a6e43e7.png)


>  If your app wanted to keep Anki's style of "learn new facts, then get quizzed", you'd create a new model with defaultModel for each card when the user first indicated they learned them. But that's not required—you can pre-initialize each flashcard with a model if you can assume the user knows them all?

Based on this, am I on the right track with this example? 
1. Set `defaultModel = ebisu.defaultModel(3, 3, 15)` for all questions
I'm guessing I just have to play around with different a, b, t values depending on how I want the app to feel?

Question: Who is the artist of 'Africa'?
Answer: Toto
Model: a=b=3, t=15 minutes

2. But in the picture when the user selects the 😃 face I have no way to `updateRecall` since time elapsed is 0. All I can do is store the time when the user saw the question.

--- 
> There's a bunch but maybe Meguro is the simplest: it's a Node.js command-line script that just reads and updates a text file containing flashcards/models: https://github.com/fasiha/meguro/

This looks promising, I'll take a look and see if I can grok anything from it.

---

`I really need to push out version 2.1 with a function to let you scale halflives, I think that's a really useful feature for real quiz apps like your Anki clone and Meguro—it's useful because, a lot of times, you'll pick the same initial model with defaultModel but in fact the user will know some cards a lot better than others. Scaling the halflife in Ebisu lets your app tell Ebisu to stretch out a model to a new halflife: you can specify any number to scale, so your app might map an "easy" quiz to 2x scale and a "hard" quiz to 0.5x scale. This isn't in Ebisu right now, it's been in a branch for a few months—I'm going to try and get it shipped this week. The code's done, it just takes me a long time to write the docstrings and update the README with the details…`

That would be amazing. Still debating on whether I want a simple yes/no system or a 3-5 tier system like Anki but it's good to have options.

**Comment by fasiha** [comment]
> Assuming all the priors are the same the prediction only depends on time elapsed since last review right?

Right. They will diverge as the various quiz histories get populated.

> For my app I can't really assume anything about what the user knows. I was hoping to quiz them / help them learn at the same time.

Got it. In this situation, just do this: when you first present a fact, and the user indicates they've committed it to memory by clicking `😀`, store `defaultModel()` and the timestamp. Then, when you actually do a quiz, call `updateRecall` with the time elapsed between that timestamp and now.

I haven't ever created a `defaultModel` *before* I show the user the flashcard for the first time, but it's ok to do this, as long as you store a timestamp with each flashcard equal to when your user first learned this flashcard. Hopefully that's straightforward? This is a bit different than the two steps you outlined, but hopefully makes sense.

> 1. But in the picture when the user selects the 😃 face I have no way to `updateRecall` since time elapsed is 0. All I can do is store the time when the user saw the question.

As above, you don't want to call `updateRecall` until you have a legitimate quiz. For the first time the user sees the flashcard, just use the output of `defaultModel` as timestamp. In addition to Meguro, there's this very barebones IPython Notebook introduction to the Ebisu workflow that might help: https://github.com/fasiha/ebisu/blob/gh-pages/EbisuHowto.ipynb

More than happy to work through any more questions you have!

**Comment by fasiha** [comment]
Hopefully it's ok to close this issue? Feel free to reopen/post more questions.
