### ISSUE TITLE
predictRecall returning negative values

### ISSUE THREAD

**Issue by eshapard** [fasiha/ebisu#8]
Hey, I made a little project that used ebisu and everything was going great. I took a break of a couple months or so and then started reviewing again. Long story short: ebisu is predicting negative recall probabilities for many items.

Passing these items, does not seem to change the probability as I would expect (to something close to 100%), I think the negative probability value is causing problems. However, I haven't dug into any specific cases to test exactly how ebisu is behaving. Will look into this further when I have the time.

A work-around may be to just reset the alpha, beta, and time values for any items with negative recall probabilities.

**Comment by fasiha** [comment]
Hello!, thanks for writing, I'm sorry you're having this problem 😞, a couple of things—
- A couple of weeks ago I published Ebisu 1.0 which changed the API a bit: `predictRecall` will return negative numbers by default (unless you pass in `exact=True` arg, see [docstrings](https://github.com/fasiha/ebisu/blob/gh-pages/doc/doc.md#predictrecallprior-tnow-exactfalse))—specifically the `log` of the probability, so the return values are still sortable: the lowest number (closest to -infinity) has the lowest recall probability. Did you by any chance update to 1.0?
- Or are you using Ebisu 0.5.x? Can you post what `(alpha, beta, t)` models and what `tnow` you pass into `predictRecall` to get negative numbers? 1.0 also greatly robustified how `updateRecall` works, and it's conceivable that numerical instabilities may arise in pre-1.0 models (e.g., with very lopsided alpha-vs-beta and very large `tnow` relative to `t`), and an example or two will help identify what the issue is.

Thank you!

**Comment by eshapard** [comment]
Ah, yes, I had started with a 0.5 version and recently upgraded, but wasn't aware of the changed feature. 

Skipping some calculations for the sake of speed sounds good. I'm glad to see that as an option. I may take advantage of that in the future. :-)

I had programmed my project to stop reviewing when the average recall probability hit a certain number, so when the review seemed endless, I started looking into the actual numbers being returned by predictRecall...

I'll set exact to True for now and hopefully none of my alpha, beta, t models created with 0.5 versions will cause any problems. Otherwise, I'll post some of the values here.

**Comment by fasiha** [comment]
Aha, excellent! Yes, the speedup is going to not matter until you reach thousands (or more) cards. I didn't even think of your clever usage of the recall probability—another thing you can do is use `exact=False` and compare the log-probability with `log(your probability threshold)`. I opted to make the default be speed instead of backwards-compatibility in part because I personally stop reviewing because I'm tired of reviewing and not necessarily because I trust the actual number for probability recall (creator tunnel vision 😭).

I might also note that the models created by 0.5 are totally fine to go through 1.0's `updateRecall`, which will rebalance them, so that the output models will stay numerically stable for much longer.
